name: Build Wheels

on: [push, pull_request]

env:
  DOCKER_IMAGE: dockcross/manylinux2014-x64


jobs:
  build_nrtest_plugin:
    name: Build nrtest-swmm plugin
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nrtest-swmm

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Build wheel
        run: |
            pip install wheel
            python setup.py bdist_wheel
      - uses: actions/upload-artifact@v2
        with:
          path: nrtest-swmm/dist/*.whl

  build_conda_wheels:
    name: Conda wheel test (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest", "windows-latest"]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        include:
          - os: windows-2022
            sys_pkgs: choco install swig
            activate: ./build-env/Scripts/activate

          - os: macos-10.15
            sys_pkgs: brew install swig ninja
            activate: source ./build-env/bin/activate

    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install required system packages
        run: ${{matrix.sys_pkgs}}

      - name: Build wheel in virtual env
        run: |
          python3 -m pip install -r build-requirements.txt
          python3 setup.py bdist_wheel

      - name: Test wheel
        run: |
          python3 -m pip install -r test-requirements.txt
          python3 -m pip install --no-index --find-links=./dist swmm_toolkit
          pytest


  build_linux_wheels:
    name: Build wheels on linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install
        run: |
          docker pull $DOCKER_IMAGE
          docker run --rm $DOCKER_IMAGE > ./dockcross
          chmod +x ./dockcross

      - name: Script
        run: ./dockcross swmm-toolkit/tools/build-wheels.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.manylinux2014_x86_64.whl



  build_win-mac_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./swmm-toolkit

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, macos-10.15]
        py: ["3.7", "3.8", "3.9", "3.10"]
        include:
          - os: windows-2022
            sys_pkgs: choco install swig
            activate: ./build-env/Scripts/activate

          - os: macos-10.15
            sys_pkgs: brew install swig ninja
            activate: source ./build-env/bin/activate

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}

      - name: Install required system packages
        run: ${{matrix.sys_pkgs}}

      - name: Build wheel in virtual env
        run: |
          python -m venv --clear ./build-env
          ${{matrix.activate}}
          python -m pip install -r build-requirements.txt
          python setup.py bdist_wheel
          deactivate

      - name: Test wheel
        run: |
          pip install -r test-requirements.txt
          pip install --no-index --find-links=./dist swmm_toolkit
          pytest

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: swmm-toolkit/dist/*.whl
