name: Build Wheels

on: [push, pull_request]

env:
  DOCKER_IMAGE: dockcross/manylinux2014-x64


jobs:
  build_linux_wheels:
    name: Build wheels on linux
    runs-on: ubuntu-18.04
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install
        run: |
          docker pull $DOCKER_IMAGE
          docker run --rm $DOCKER_IMAGE > ./dockcross
          chmod +x ./dockcross

      - name: Script
        run: ./dockcross swmm-toolkit/tools/build-wheels.sh
      
      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/swmm_toolkit*.whl



  build_win-mac_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:  
        working-directory: ./swmm-toolkit
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2016, macos-10.15]
        py: [3.6, 3.7, 3.8, 3.9]
        
        include:
          - os: windows-2016
            build-reqs: choco install swig
            activate: ./build-env/Scripts/activate
            
          - os: macos-10.15
            build-reqs: brew install libomp swig
            activate: source ./build-env/bin/activate
                
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}

      - name: Install build requirements
        run: ${{matrix.build-reqs}}

      - name: Build wheel in virtual env
        run: |
          python -m venv --clear ./build-env
          ${{matrix.activate}}
          python -m pip install -r build-requirements.txt
          python setup.py bdist_wheel
          deactivate
          
      - name: Test wheel
        run: |
          pip install -r test-requirements.txt
          pip install --no-index --find-links=./dist swmm_toolkit
          pytest

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ${{defaults.working-directory}}/dist/*.whl
